### ISSUE TITLE
Docker Hub: Something went wrong!

### ISSUE THREAD

**Issue by Hutch79** [fitchmultz/docker-qbittorrentvpn#16]
Hey fitchmultz,

First of all, thanks for the great work with the project, it's really useful to me!

I wanted to update my docker stack today and noticed it can't pull this image.
After checking docker hub, it was clear that something is wrong, because I've only gotten an error page.

I don't know if you're already aware of this issue, therefore the issue here.

**Comment by fitchmultz** [comment]
Sorry, switch to using the GitHub docker repository instead. ghcr.io/fitchmultz/docker-qbittorrentvpn:latest
